name: Build

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare files
      run: make linux

    - name: Upload tar.gz
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux-amd64.tar.gz
        name: pdk-environment-linux-amd64-${TAG}.tar.gz
        label: Linux Package (amd64)


  macos:
    name: MacOS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare files
      run: make macos

    - name: Upload tar.gz
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/macos-amd64.tar.gz
        name: pdk-environment-macos-amd64-${TAG}.tar.gz
        label: MacOS Package (amd64)


  win64:
    name: Windows
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare files
      run: make win

    - name: Upload zip
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win-amd64.zip
        name: pdk-environment-win-amd64-${TAG}.zip
        label: Windows Package (amd64)
