name: Package

on:
  push:
    branches:
      - master
      - main
  release:
    types: 
      - published

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    outputs:
      version: ${{ env.VERSION }}

    steps:
      - name: Prepare version labels
        uses: k15g/action-version-labels@v1

  linux:
    name: Linux
    runs-on: ubuntu-latest
    needs:
      - init

    strategy:
      matrix:
        arch:
          - amd64
          - arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load environment variables
      uses: k15g/action-load-env@edge

    - name: Prepare files
      run: make linux-${{ matrix.arch }}

    - name: Upload tar.gz
      uses: k15g/action-github-asset-upload@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: target/pkg/linux-${{ matrix.arch }}.tar.gz
        name: pdk-environment-linux-${{ matrix.arch }}-${{ needs.init.outputs.version }}.tar.gz
        label: Linux bundle (${{ matrix.arch }})


  macos:
    name: MacOS
    runs-on: ubuntu-latest
    needs:
      - init

    strategy:
      matrix:
        arch:
          - amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load environment variables
      uses: k15g/action-load-env@edge

    - name: Prepare files
      run: make macos-${{ matrix.arch }}

    - name: Upload tar.gz
      uses: k15g/action-github-asset-upload@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: target/pkg/macos-${{ matrix.arch }}.tar.gz
        name: pdk-environment-macos-${{ matrix.arch }}-${{ needs.init.outputs.version }}.tar.gz
        label: MacOS bundle (${{ matrix.arch }})


  win64:
    name: Windows
    runs-on: ubuntu-latest
    needs:
      - init

    strategy:
      matrix:
        arch:
          - amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load environment variables
      uses: k15g/action-load-env@edge

    - name: Prepare files
      run: make win-${{ matrix.arch }}

    - name: Upload zip
      uses: k15g/action-github-asset-upload@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: target/pkg/win-${{ matrix.arch }}.zip
        name: pdk-environment-win-${{ matrix.arch }}-${{ needs.init.outputs.version }}.zip
        label: Windows bundle (${{ matrix.arch }})
